version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - run:
        name: yarn
        command: npm i -g yarn
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: install-yarn wee
        command: yarn install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
      - run:
        name: build
        command: yarn start
  test:        
    - run:
      name: Jest Suite
      command: yarn jest tests --ci --testResultsProcessor="jest-junit" --runInBand
      environment:
        JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
    - run:
      name: test
      command: npm testCI #e2e not implemented
    - store_test_results:
      path: reports/junit
    - store_artifacts:
      path: reports/junit
    - run:
      name: code-coverage
      command: './node_modules/.bin/nyc report --reporter=text-lcov'
    - store_artifacts:
      path: test-results.xml
      prefix: tests
    - store_artifacts:
      path: coverage
      prefix: coverage
    - store_test_results:
      path: test-results.xml
  deploy-stage:
    # branches:
    #   only:
    #     - master
    commands:
      - yarn global add now
      - now -t ${NOW_TOKEN}
      - now -t ${NOW_TOKEN} alias makpal
  deploy-production:
    # branches:
    #   only:
    #     - production
    commands:
      - yarn global add now
      - now -t ${NOW_TOKEN}
      - now -t ${NOW_TOKEN} alias makpal-prod

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy-stage:
          # requires:
          #   - build
          #   - test
          filters:
            branches:
              only: master
      - deploy-production:
          # requires:
          #   - build
          #   - test
          filters:
            branches:
              only: production    